### ISSUE TITLE
Usage of SVG nodes with namespace results in compile error

### ISSUE THREAD

**Issue by adrobisch** [OlivierBlanvillain/monadic-html#34]
Hi, 
thanks for monadic-html, I really like it! I am trying to find out how to use inline SVG nodes and tried something like this:
```scala
import mhtml._
import scala.xml.Node
import org.scalajs.dom

import scala.scalajs.js.JSApp

object TestApp extends JSApp {
  def main(): Unit = {
    val radius: Var[Int] = Var(100)

    val component =
      <div>
        <svg height="100" width="100" xmlns="http://www.w3.org/2000/svg">
          <circle cx="50" cy="50" r={radius.map(_.toString)} stroke="black" stroke-width="3" fill="red" />
        </svg>
      </div>

    mount(dom.document.body, component)
  }
}  
```

This results in a compile error I am unable to resolve: 
```
[error] /home/adrobisch/dev/git/mhtml-test/src/main/scala/TestApp.scala:15: type NamespaceBinding is not a member of package xml
[error]         <svg height="100" width="100" xmlns="http://www.w3.org/2000/svg">
```

Without the namespace it compiles, but I can't see the svg in the browser, which is why I added it in the first place (http://stackoverflow.com/questions/22557669/svg-added-to-dom-using-javascript-is-not-visible).

What would be the proper way to define this kind of attributes with monadic-html?

**Comment by OlivierBlanvillain** [comment]
That's a bug! Apparently `scalac` generate different code for `xmlns` prefixed attributes, which we didn't take into account in our custom `scala.xml._` implementation, hence the compilation error.

**Comment by OlivierBlanvillain** [comment]
I've just published `0.2.1` with a fix, let me know if that works for you!

**Comment by adrobisch** [comment]
Thanks a lot, it works regarding compilation and visible dom, still not seeing the svg in the browser though. It turned out that `createElementNS` is needed for SVG nodes, I created a PR for that: https://github.com/OlivierBlanvillain/monadic-html/pull/36
